<style type="text/css">
	#picchooser {
		width: 600px;
		overflow: scroll;
		height: 110px;
		border: 4px solid #e5e5e5;
	}

	.url, .hidden {
		display: none;
	}

	#picchooser div {
		display: inline;
        position:relative;
	}
    .pic { border:3px solid #fff; }
    .pico { border:3px solid #999; }
    .nr { position:absolute; top:-55px; left:55px; font-size:30px; }
</style>
<?php
$_product = Mage::registry('current_product');
$_images = $_product->getMediaGalleryImages();
$selected = $_product->getData('clipgenerator_images_select');
$selArr = explode(';', trim($selected, ';'));
?>

<?php if ($_images): ?>
	<div id="picchooser">
		<?php foreach ($_images as $_image): ?>
            <?php $pos = array_search($_image->getUrl(), $selArr); ?>
			<div>
                <span class="nr">
                    <?php if($pos !== false): ?>
                        <?=$pos+1?>
                    <?php endif; ?>
                </span>
				<?php if (strstr($selected, $_image->getUrl())): ?>
					<img class="pico" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(80, 80); ?>" />
				<?php else: ?>
					<img class="pic" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(80, 80); ?>" />
				<?php endif; ?>
				<span class="url"><?= $_image->getUrl() ?></span>
			</div>
		<?php endforeach; ?>
	</div>
<?php else: ?>
	<?= Mage::helper('clipgenerator')->__('Bitte laden Sie zuerst Bilder hoch.'); ?>
<?php endif; ?>

<script type="text/javascript">
    var title = "<?= str_replace('"', '\'', $_product->getName()) ?>";
    var description = <?= json_encode(str_replace('"', '\'', strip_tags($_product->getDescription()))) ?>;
    var keywords = <?= json_encode(str_replace(array("\r\n", "\r", "\n"), " ", $_product->getMetaKeyword())) ?>;
    var vTitle = "<?=$_product->getData('clipgenerator_title')?>";
    var vDesc = <?= json_encode($_product->getData('clipgenerator_description')) ?>;
    var vKey = "<?= $_product->getData('clipgenerator_keywords')?>";
	$('clipgenerator_images_select').addClassName('hidden');
	document.observe('dom:loaded', function () {
        if(title != '' && !vTitle) {
            $('clipgenerator_title').writeAttribute('value', title);
        }
        if(description != '' && !vDesc) {
            $('clipgenerator_description').innerHTML = description;
        }
        if(keywords != '' && !vKey) {
            $('clipgenerator_keywords').writeAttribute('value', keywords);
        }
        $('clipgenerator_video_id').up().up().hide();
		$$('.pico').each(function (el) {
			el.setOpacity(0.5);
		});
		$('picchooser').observe('click', function (event) {
			pic = Event.element(event);
			if (pic.readAttribute('class') == 'pic') {
				pic.setOpacity(0.5);
				pic.addClassName('pico');
				pic.removeClassName('pic');
				addUrl = ';' + pic.up().select('.url')[0].innerHTML;
				$('clipgenerator_images_select').writeAttribute('value', $('clipgenerator_images_select').readAttribute('value') + addUrl);
                reCount();
			} else if (pic.readAttribute('class') == 'pico') {
				pic.addClassName('pic');
				pic.removeClassName('pico');
				pic.setOpacity(1);
				rmUrl = ';' + pic.up().select('.url')[0].innerHTML;
				$('clipgenerator_images_select').writeAttribute('value', $('clipgenerator_images_select').readAttribute('value').replace(rmUrl, ''));
                pic.up().select('.nr')[0].innerHTML = '';
                reCount();
			}
		});
	});

    function reCount() {
        var arrImg = $('clipgenerator_images_select').readAttribute('value').split(';');
        counter = 0;
        arrImg.each(function(el) {
            if(el) {
                $$('.url').each(function(nel) {
                    if(nel.innerHTML == el) {
                        counter = counter + 1;
                        nel.up().select('.nr')[0].innerHTML = counter;
                    }
                });
            }
        });
    }
</script>